name: genai-agent-doc-system

channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - cpuonly
  - pip:
      - streamlit
      - langchain
      - langchain-community
      - langchain-chroma
      - langchain-google-genai
      - langchain-openai
      - langgraph
      - chromadb
      - pandas
      - pypdf
      - openpyxl
      - python-dotenv
      - tiktoken
      - google-generativeai
      - langchain-huggingface
      - sentence-transformers